### ISSUE TITLE
Problem in reading binary UFF (or UFB)

### ISSUE THREAD

**Issue by hdemontis** [ladisk/pyuff#61] opened 2022-01-26 14:19 UTC
Hi everyone,

- Windows 10
- Python 3.9.7
- `pyuff` version : 2.0

I experience issues when opening and reading datasets stored in a binary UFB file. This show me the following error :
```
File "C:\Anaconda3\lib\site-packages\pyuff\pyuff.py", line 280, in read_sets
    raise Exception('Error when reading ' + str(ii) + '-th data-set: ' + msg.args[0])

Exception: Error when reading 0-th data-set: Error reading data-set #58b
```

My UFB file can be accessed using this toolbox in Matlab : https://fr.mathworks.com/matlabcentral/fileexchange/70464-uff-file-reading-and-writing
Is someone have this problem too ? Any way to get around ?

Thanks,

**Comment by jankoslavic** [comment] 2022-01-26 18:47
Dear @hdemontis can you please provide the minimal code to reproduce the error?

**Comment by hdemontis** [comment] 2022-01-28 09:38
Hi,
```
import pyuff
from os.path import join as pjoin

# name of file
sigFile = "fileName.ufb"

# Open file UFB
uff_file = pyuff.UFF(sigFile)

# read all datasets
data = uff_file.read_sets()
```

**Comment by jankoslavic** [comment] 2022-01-28 10:58
ps: please add the file where you have problems.

**Comment by jankoslavic** [comment] 2022-02-25 06:32
Is this issue still relevant? @hdemontis can you please provide the test file?

**Comment by Albert-Alarcon** [comment] 2022-07-21 21:31
Hi everyone,

i'm experiencing a similar problem when reading a binary dataset58 file.  Below's the raised error. Any idea?

Thanx for your help!

```
Traceback (most recent call last):
  File "C:\Users\h06756\AppData\Local\Programs\Python\Python38\lib\site-packages\pyuff\datasets\dataset_58.py", line 226, in _extract58
    dset.update(_parse_header_line(split_header[10], 4, [10, 5, 5, 5, 21, 21], [2, 2, 2, 2, 1, 1],
  File "C:\Users\h06756\AppData\Local\Programs\Python\Python38\lib\site-packages\pyuff\tools.py", line 61, in _parse_header_line
    fields_out.update({key: int(fields_from_line[n])})
ValueError: invalid literal for int() with base 10: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\h06756\AppData\Local\Programs\Python\Python38\lib\site-packages\pyuff\pyuff.py", line 278, in read_sets
    dset.append(self._read_set(ii))
  File "C:\Users\h06756\AppData\Local\Programs\Python\Python38\lib\site-packages\pyuff\pyuff.py", line 366, in _read_set
    dset = _extract58(block_data)
  File "C:\Users\h06756\AppData\Local\Programs\Python\Python38\lib\site-packages\pyuff\datasets\dataset_58.py", line 305, in _extract58
    raise Exception('Error reading data-set #58b')
Exception: Error reading data-set #58b

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_pyuff.py", line 34, in <module>
    red_data = uff_file.read_sets()
  File "C:\Users\h06756\AppData\Local\Programs\Python\Python38\lib\site-packages\pyuff\pyuff.py", line 280, in read_sets
    raise Exception('Error when reading ' + str(ii) + '-th data-set: ' + msg.value)
AttributeError: 'Exception' object has no attribute 'value'
```

**Comment by jankoslavic** [comment] 2022-07-22 05:22
It looks like you have an empty field. @Albert-Alarcon please provide minimal code to reproduce your error.

**Comment by Albert-Alarcon** [comment] 2022-07-22 07:23
Thanks for your answer @jankoslavic 
here's the very simple code

```
import pyuff
uff_file = pyuff.UFF('20220412_105038.UNVB')
my_data = uff_file.read_sets()
```

You'll find attached the test file (note that I have changed the extension to .txt so github accepts to upload the file)
[20220412_105038.txt](https://github.com/ladisk/pyuff/files/9165586/20220412_105038.txt)

Thanks again for your help!

**Comment by jankoslavic** [comment] 2022-07-25 09:42
Dear @Albert-Alarcon !
The header in your file:
`    -1
    58b     1     2          11     1048576     0     0           0           0
B602_Parc Equipements;GU Fessenheim;VGL G2;20220412_105038;               
Puissance Active MW = 9.75;                                                     
Puissance Réactive MVAR = 1.99;                                                 
De 1 à 60% Pmax;                                                                
T-5.12 kHz-256K (MVP;                                                           
    1         0    0         0 TT_SIGN            1   0 NONE               0   0
         2    262144         1            0 1.953125e-04            0
        17    0    0    0 Duree (s)            s                   
        -1    0    0    0 TT_SIGN                                  
         0    0    0    0 NONE                 NONE                
         0    0    0    0 NONE                 NONE                
`
is not formated with regard to the datafile 58 specifications.
I think you have a problem with the software where you are exporting from.

**Comment by Albert-Alarcon** [comment] 2022-07-27 08:07
Thanks for the answer @jankoslavic  ! 
I'm going to check with the software developpers to solve this export. 
Do you know which field is incorrect regarding to the 58 datafile specs?

**Comment by jankoslavic** [comment] 2022-07-27 12:22
It looks like the header is not properly divided with newlines.

**Comment by WHX1141952774** [comment] 2024-10-08 08:56
I have a file(.bunv),  the header is:

    -1
    58b     1     2          11      889600     0     0           0           0
MPS set1 Dof1
NONE
08-Oct-24 10:27:07
NONE
NONE
    1         0    0         0 1+Z                1   3 NONE               0   0
         2    222400         1  0.00000E+00  3.12500E-04  0.00000E+00
        17    0    0    0 Time                 s                   
        12    0    0    0 Acceleration         m/s2                
         0    0    0    0 NONE                 NONE                
         0    0    0    0 NONE                 NONE 

My simple code is:

import pyuff

uff_file = pyuff.UFF('filename.bunv')
type(uff_file), uff_file
(pyuff.pyuff.UFF, <pyuff.pyuff.UFF at 0x18c0ba698b0>)

set_types = uff_file.get_set_types()
array([58, 58, 58, 58])

but it have AttributeError:

error                                     Traceback (most recent call last)
File D:\Anaconda\envs\wet_dry\lib\site-packages\pyuff\datasets\dataset_58.py:1078, in _extract58(block_data)
   1076 if (dset['ord_data_type'] == 2) or (dset['ord_data_type'] == 5):
   1077     # single precision - 4 bytes
-> 1078     values = np.asarray(struct.unpack('%c%sf' % (bo, int(len(split_data) / 4)), split_data), 'd')
   1079 else:
   1080     # double precision - 8 bytes

error: unpack requires a buffer of 889600 bytes

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
File D:\Anaconda\envs\wet_dry\lib\site-packages\pyuff\pyuff.py:260, in UFF.read_sets(self, setn)
    259     for ii in read_range:
--> 260         dset.append(self._read_set(ii))
    261 except Exception as msg:

File D:\Anaconda\envs\wet_dry\lib\site-packages\pyuff\pyuff.py:354, in UFF._read_set(self, n)
    353 elif self._set_types[int(n)] == 58:
--> 354     dset = _extract58(block_data)
    355 elif self._set_types[int(n)] == 82:

File D:\Anaconda\envs\wet_dry\lib\site-packages\pyuff\datasets\dataset_58.py:1135, in _extract58(block_data)
   1134 except:
-> 1135     raise Exception('Error reading data-set #58b')
   1136 return dset

Exception: Error reading data-set #58b

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
Cell In[6], line 1
----> 1 datasets = uff_file.read_sets()

File D:\Anaconda\envs\wet_dry\lib\site-packages\pyuff\pyuff.py:262, in UFF.read_sets(self, setn)
    260         dset.append(self._read_set(ii))
    261 except Exception as msg:
--> 262     raise Exception('Error when reading ' + str(ii) + '-th data-set: ' + msg.value)
    263 except:
    264     raise Exception('Error when reading data-set(s)')

AttributeError: 'Exception' object has no attribute 'value'

**Comment by jankoslavic** [comment] 2024-10-08 08:58
Hi @WHX1141952774 can you please add the file as attachment?

**Comment by WHX1141952774** [comment] 2024-10-08 09:50
> Hi @WHX1141952774 can you please add the file as attachment? Ok. Now I see the file.

Hello, expert. what is the reason for this AttributeError? How can it be resolved?

**Comment by jasasonc** [comment] 2024-10-09 09:56
Hi @WHX1141952774, the problem might be related to file formatting (not in accordance to the 58b specification). I can check your file, but the file link you provided does not seem to work.

**Comment by WHX1141952774** [comment] 2024-10-09 10:09
> Hi @WHX1141952774, the problem might be related to file formatting (not in accordance to the 58b specification). I can check your file, but the file link you provided does not seem to work.

You'll find attached the test file (I have changed the extension to .txt so github accepts to upload the file)
[MPSTD#Set001_2024_10_08_10_27_07.txt](https://github.com/user-attachments/files/17306253/MPSTD.Set001_2024_10_08_10_27_07.txt)

Please refer to this file, Thanks for your help!

**Comment by jankoslavic** [comment] 2024-10-09 10:57
@jasasonc great work! I suggest adding a warning, which would better describe that the file might not be up to speficifications. @jasasonc are you willing to prepare a PR?

**Comment by jasasonc** [comment] 2024-10-09 11:07
@jankoslavic I agree, the current warning does not provide useful information about the file problem. I will prepare a PR.

**Comment by jankoslavic** [comment] 2024-11-06 12:08
@WHX1141952774 please check the latest pull request where a fix tools was added to correct files with not proper implementation of new line.

**Comment by WHX1141952774** [comment] 2024-11-06 13:09
> @WHX1141952774 please check the latest pull request where a fix tools was added to correct files with not proper implementation of new line.
> 
> ```python
> pyuff.fix_58b('./data/MPSTD#Set001_2024_10_08_10_27_07.uff')
> corrected_file = pyuff.UFF('./data/MPSTD#Set001_2024_10_08_10_27_07_fixed.uff')
> ```

OK, thank you very much. That's just great, good job！！！

**Comment by jankoslavic** [comment] 2024-11-06 18:36
Thank you for the feedback. I will close this issue and prepare a release

**Closed by jankoslavic** 2024-11-06 18:36 UTC
